// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJVp41GodLmQLsZpTNoi6JZ8dEEvxzeLo',
    appId: '1:822752724214:web:94eddbac5974b4236518d7',
    messagingSenderId: '822752724214',
    projectId: 'deliverytrackingapp-bc810',
    authDomain: 'deliverytrackingapp-bc810.firebaseapp.com',
    databaseURL: 'https://deliverytrackingapp-bc810-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'deliverytrackingapp-bc810.firebasestorage.app',
    measurementId: 'G-XCF62EPX6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCESHtkD-wwWtx2OX2eMiASUtF4KZG8ynQ',
    appId: '1:822752724214:android:cc0282651163849c6518d7',
    messagingSenderId: '822752724214',
    projectId: 'deliverytrackingapp-bc810',
    databaseURL: 'https://deliverytrackingapp-bc810-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'deliverytrackingapp-bc810.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvXTKBBOzrTIL15NDfRYrztzv18l_rCt0',
    appId: '1:822752724214:ios:80070d42046ed1c86518d7',
    messagingSenderId: '822752724214',
    projectId: 'deliverytrackingapp-bc810',
    databaseURL: 'https://deliverytrackingapp-bc810-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'deliverytrackingapp-bc810.firebasestorage.app',
    iosBundleId: 'com.example.ostadFirebaseAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvXTKBBOzrTIL15NDfRYrztzv18l_rCt0',
    appId: '1:822752724214:ios:80070d42046ed1c86518d7',
    messagingSenderId: '822752724214',
    projectId: 'deliverytrackingapp-bc810',
    databaseURL: 'https://deliverytrackingapp-bc810-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'deliverytrackingapp-bc810.firebasestorage.app',
    iosBundleId: 'com.example.ostadFirebaseAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJVp41GodLmQLsZpTNoi6JZ8dEEvxzeLo',
    appId: '1:822752724214:web:5126d76877f2600d6518d7',
    messagingSenderId: '822752724214',
    projectId: 'deliverytrackingapp-bc810',
    authDomain: 'deliverytrackingapp-bc810.firebaseapp.com',
    databaseURL: 'https://deliverytrackingapp-bc810-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'deliverytrackingapp-bc810.firebasestorage.app',
    measurementId: 'G-MVXECQXCWF',
  );
}
